name: dw9_vakinha_burger_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_awesome_select: ^6.5.0
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  top_snackbar_flutter: ^3.2.0
  validatorless: ^1.2.4

dev_dependencies:
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800
