name: dw9_vakinha_burger_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_awesome_select: ^6.5.0
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  match: ^0.4.1
  shared_preferences: ^2.0.17
  top_snackbar_flutter: ^3.0.0+1
  validatorless: ^1.2.3

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  dart_code_metrics: any
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  match_generator: ^0.4.1
  mocktail: ^0.3.0
  test: ^1.22.1

dependency_overrides:
  test_api: ^0.4.18

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800
