name: dw9_vakinha_burger_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.5

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_awesome_select: ^6.5.0
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  top_snackbar_flutter: ^3.0.0+1
  validatorless: ^1.2.3

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  dart_code_metrics: ^5.7.5
  mocktail: ^0.3.0
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800
